---

#requires following env variables
# HOST: host to connect to, can be defined in inventory file. e.g. user@host or host
# NEXTJS_REPO_ID: org/repo 
# NEXTJS_REPO_BRANCH: branch to checkout
# STRAPI_REPO_ID: org/repo
# STRAPI_REPO_BRANCH: branch to checkout
# GH_USER: github username
# GH_TOKEN: github token
# NEXTJS_ENV the env to use for nextjs
# STRAPI_ENV the env to use for strapi


- hosts: "{{ HOST }}"
  gather_facts: false

  tasks:
    - name: wait for connection
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: checkout nextjs repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}@github.com/{{ NEXTJS_REPO_ID }}
        dest: ~/nextjs
        version: "{{ NEXTJS_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: nextjs_repo

    - name: checkout strapi repo
      git:
        repo: https://{{ GH_USER }}:{{ GH_TOKEN }}@github.com/{{ STRAPI_REPO_ID }}
        dest: ~/strapi
        version: "{{ STRAPI_REPO_BRANCH }}"
        force: yes
        recursive: yes
        clone: yes
        depth: 1
      register: strapi_repo

    - name: install pm2 using npm
      become: yes
      become_user: bitnami
      shell:
        cmd: sudo npm install pm2 -g
        executable: /bin/bash

    - name: install deps for nextjs
      npm:
        path: ~/nextjs
        production: yes
        registry: https://registry.npmjs.org/

    - name: install deps for strapi
      npm:
        path: ~/strapi
        production: yes
        registry: https://registry.npmjs.org/

    - name: copy nextjs env file
      become_user: bitnami
      copy:
        content: "{{ NEXTJS_ENV }}"
        dest: ~/nextjs/.env.local

    - name: copy strapi env file
      become_user: bitnami
      copy:
        content: "{{ STRAPI_ENV }}"
        dest: ~/strapi/.env

    - name: replace nextjs env file spaces with newlines
      become_user: bitnami
      shell:
        cmd: sed -i 's/ /\n/g' ~/nextjs/.env.local
        executable: /bin/bash

    - name: replace strapi env file spaces with newlines
      become_user: bitnami
      shell:
        cmd: sed -i 's/ /\n/g' ~/strapi/.env
        executable: /bin/bash

    - name: build nextjs
      command: npm run build
      args:
        chdir: ~/nextjs

    - name: build strapi 
      command: npm run build
      args:
        chdir: ~/strapi

    - name: delete old pm2 processes
      become_user: bitnami
      command: pm2 delete all
      ignore_errors: yes

    - name: start nextjs with pm2
      become_user: bitnami
      command: pm2 start npm --name "nextjs" -- start
      args:
        chdir: ~/nextjs

    - name: start strapi with pm2
      become_user: bitnami
      command: pm2 start npm --name "strapi" -- start -- --env production
      args:
        chdir: ~/strapi



